-- Аккаунты пользователей. Профиль (анкета) хранится отдельно и появится в следующей миграции.
-- SQL написан переносимо: выполняется и в PostgreSQL, и в H2 (режим PostgreSQL) для тестов.
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255)             NOT NULL,
    password_hash VARCHAR(100)             NOT NULL,
    role          VARCHAR(20)              NOT NULL,   -- USER | ADMIN
    status        VARCHAR(20)              NOT NULL,   -- ACTIVE | BLOCKED
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);
