-- Анкеты, справочник интересов и фото. Все внешние ключи каскадные:
-- удаление аккаунта убирает анкету, её интересы и фото одним действием.

CREATE TABLE interests (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50) NOT NULL,
    category VARCHAR(30) NOT NULL,      -- ACTIVE | CULTURE | FOOD | HOBBY | LIFESTYLE | TECH
    CONSTRAINT uq_interests_name UNIQUE (name)
);

CREATE TABLE profiles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT                   NOT NULL,
    display_name VARCHAR(50)              NOT NULL,
    birth_date   DATE                     NOT NULL,
    gender       VARCHAR(10)              NOT NULL,   -- MALE | FEMALE | OTHER
    looking_for  VARCHAR(10)              NOT NULL,   -- MALE | FEMALE | EVERYONE
    age_min      INT                      NOT NULL,
    age_max      INT                      NOT NULL,
    city         VARCHAR(100)             NOT NULL,
    bio          VARCHAR(1000),
    contact      VARCHAR(100)             NOT NULL,   -- показывается только после взаимного лайка
    visible      BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_profiles_city ON profiles (city);

CREATE TABLE profile_interests (
    profile_id  BIGINT NOT NULL,
    interest_id BIGINT NOT NULL,
    PRIMARY KEY (profile_id, interest_id),
    CONSTRAINT fk_pi_profile  FOREIGN KEY (profile_id)  REFERENCES profiles (id)  ON DELETE CASCADE,
    CONSTRAINT fk_pi_interest FOREIGN KEY (interest_id) REFERENCES interests (id) ON DELETE CASCADE
);

CREATE TABLE profile_photos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id   BIGINT                   NOT NULL,
    content_type VARCHAR(50)              NOT NULL,
    size_bytes   INT                      NOT NULL,
    data         BYTEA                    NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_photo_profile UNIQUE (profile_id),
    CONSTRAINT fk_photo_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);

-- Стартовый справочник интересов (администратор может его расширять через API)
INSERT INTO interests (name, category) VALUES
    ('Спорт', 'ACTIVE'), ('Бег', 'ACTIVE'), ('Йога', 'ACTIVE'), ('Велосипед', 'ACTIVE'),
    ('Походы', 'ACTIVE'), ('Танцы', 'ACTIVE'), ('Плавание', 'ACTIVE'),
    ('Кино', 'CULTURE'), ('Музыка', 'CULTURE'), ('Книги', 'CULTURE'), ('Театр', 'CULTURE'),
    ('Искусство', 'CULTURE'), ('Фотография', 'CULTURE'), ('Сериалы', 'CULTURE'), ('Аниме', 'CULTURE'),
    ('Кулинария', 'FOOD'), ('Кофе', 'FOOD'), ('Вино', 'FOOD'), ('Рестораны', 'FOOD'),
    ('Видеоигры', 'HOBBY'), ('Настольные игры', 'HOBBY'), ('Рыбалка', 'HOBBY'), ('Рукоделие', 'HOBBY'), ('Садоводство', 'HOBBY'),
    ('Путешествия', 'LIFESTYLE'), ('Животные', 'LIFESTYLE'), ('Природа', 'LIFESTYLE'), ('Мода', 'LIFESTYLE'),
    ('Психология', 'LIFESTYLE'), ('Волонтёрство', 'LIFESTYLE'), ('Иностранные языки', 'LIFESTYLE'),
    ('Технологии', 'TECH'), ('Наука', 'TECH'), ('Программирование', 'TECH'), ('Автомобили', 'TECH');
