-- Реакции (лайк / пропуск) и матчи (взаимные лайки).
-- Пара анкет в reactions уникальна: повторная реакция обновляет тип, а не создаёт дубликат.

CREATE TABLE reactions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_profile_id BIGINT                   NOT NULL,
    to_profile_id   BIGINT                   NOT NULL,
    reaction_type   VARCHAR(10)              NOT NULL,   -- LIKE | SKIP
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_reaction_pair UNIQUE (from_profile_id, to_profile_id),
    CONSTRAINT fk_reaction_from FOREIGN KEY (from_profile_id) REFERENCES profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_reaction_to   FOREIGN KEY (to_profile_id)   REFERENCES profiles (id) ON DELETE CASCADE
);

CREATE INDEX idx_reactions_target ON reactions (to_profile_id, reaction_type);

-- profile_a_id всегда меньше profile_b_id, поэтому пара хранится в одном экземпляре
CREATE TABLE profile_matches (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_a_id BIGINT                   NOT NULL,
    profile_b_id BIGINT                   NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_match_pair UNIQUE (profile_a_id, profile_b_id),
    CONSTRAINT fk_match_a FOREIGN KEY (profile_a_id) REFERENCES profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_match_b FOREIGN KEY (profile_b_id) REFERENCES profiles (id) ON DELETE CASCADE
);

CREATE INDEX idx_matches_b ON profile_matches (profile_b_id);
